export { clamp } from './clamp'
export { computeClampedDt } from './computeClampedDt'
export { computeContentBounds, type ContentBounds } from './computeContentBounds'
export { createGameSettingsProvider, type CreateGameSettingsProviderConfig, type CreateGameSettingsProviderResult, type GameSettingsContextValue, type GameSettingsProviderProps } from './createGameSettingsProvider'
export { FakeLandscapeView, type FakeLandscapeViewProps } from './FakeLandscapeView'
export { type EdgeInsets, rotateInsets } from './insets'
export { type OrientationLockSettings } from './OrientationLockContext'
export { type OrientationMode } from './OrientationMode'
export { OrientationProvider, type OrientationProviderProps } from './OrientationProvider'
export { getFixedZoneRotation, getOpposingZoneRotation, getViewRotation, rotateDimensions, toRotationStyle, type ViewRotation } from './rotation'
export { RotationAwareStatusBar, type RotationAwareStatusBarProps } from './RotationAwareStatusBar'
export { SettingsAndProfilesGate, type SettingsAndProfilesGateComponentProps, type SettingsAndProfilesGateProps } from './SettingsAndProfilesGate'
export { useGameLoop, type UseGameLoopOptions } from './useGameLoop'
export { useIsTouchPrimaryDevice } from './useIsTouchPrimaryDevice'
export { useOrientationLock } from './useOrientationLock'
export { type DeviceMotionListener, type DeviceMotionMeasurement, type DeviceMotionModule, getOrientationSnapshot, type OrientationState, useOrientationState } from './useOrientationState'
export { useRotatedWindowDimensions } from './useRotatedWindowDimensions'
export { useRotation } from './useRotation'
export { type SettledLayoutSize, useSettledLayout, type UseSettledLayoutResult } from './useSettledLayout'
export { useSettledWindowDimensions } from './useSettledWindowDimensions'
export { type ThemedRootStackOptions, useThemedRootBackground } from './useThemedRootBackground'
export { add, distance, dot, length, normalize, scale, subtract, type Vec2 } from './Vec2'
